version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URL=mongodb://db:27017/webShop
      - JWT_SECRET=kjhgfdsakjhgfsdakjhgfsaiuytweqekhgjvsakjhbvskjhgasdkjhfgskajhfgjkhsaghjkdfgasjhhghgfhfhffhgffffffffshdhdhdhjhgbdysfghjsdfasdfguysfdguywguytf123456789234567893456789
  frontend:
    build:
      dockerfile: Dockerfile.client
      args:
        APP_WEBSHOP_API: http://localhost:4000
    ports:
      - "3000:3000"

  db:
    image: mongo:6.0.2
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - /data/db
